version: "3"
services:
  gitlab:
    image: gitlab/gitlab-ce:9.1.3-ce.0
    hostname: 'gitlab.example.com'
    environment:
      - GITLAB_RELATIVE_URL_ROOT=/gitlab
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com'
    deploy:
     placement:
        constraints: [node.role == worker]
     labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/gitlab
        - com.df.port=80
    networks:
      - gitlab
      - proxy_proxy
    volumes:
        -  gitlab:/etc/gitlab
        -  gitlab_log:/var/log/gitlab
        -  gitlab_var:/var/opt/gitlab
networks:
  proxy_proxy:
    external: true
  gitlab:
     driver: overlay
     ipam:
      config:
      - subnet: 172.28.0.0/24
volumes:
  gitlab:
   driver: convoy
  gitlab_log:
   driver: convoy
  gitlab_var:
   driver: convoy