version: "3"
services:
  traefik:
    image: traefik
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: --docker --docker.swarmmode --docker.domain=example.com --docker.watch --logLevel=DEBUG --docker.endpoint=tcp://socat:2375 --web
    networks:
      - socat
      - traefik-net
    deploy:
      mode: global
      placement:
        constraints: [node.labels.zone == dmz]
  socat:
    image: rancher/socat-docker
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - socat
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints: [node.role == manager]
  visualizer:
    image: dockersamples/visualizer:stable
    stop_grace_period: 1m30s
    networks:
      - traefik-net
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints: 
          - node.role == manager
      labels:
       - "traefik.port=8080"
       - "traefik.docker.network=traefik_traefik-net"
       - "traefik.frontend.rule=Host:swarm.example.com"
networks:
    traefik_default:
     driver: overlay
     ipam:
      config:
      - subnet: 172.24.0.0/24
    traefik-net:
     driver: overlay
     ipam:
      config:
      - subnet: 172.25.0.0/24
    socat:
     driver: overlay
     ipam:
      config:
      - subnet: 172.23.0.0/24