version: "3"
services:
  traefik:
    image: gtosi/traefik 
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: --docker --docker.swarmmode --docker.domain=example.com --docker.watch --logLevel=DEBUG --web
    networks:
      - traefik-net
    deploy:
      placement:
        constraints: [node.role == manager]
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8000:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
networks:
    traefik-net:
     driver: overlay
     ipam:
      config:
      - subnet: 172.25.0.0/24