version: "3"
services:
  web:
    image: emilevauge/whoami
    deploy:
     labels:
      - "traefik.port=80"
      - "traefik.docker.network=traefik-net"
      - "traefik.frontend.rule=Host:whoami0.example.com"
    networks:
      - web
      - traefik_traefik-net
networks:
  traefik_traefik-net:
    external: true
  web:
     driver: overlay
     ipam:
      config:
      - subnet: 172.26.0.0/24