version: "3"
services:
  jenkins:
    image: jenkinsci/jenkins
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    deploy:
     placement:
        constraints: [node.role == worker]
     labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/jenkins
        - com.df.port=8080
    networks:
      - jenkins
      - proxy_proxy
networks:
  proxy_proxy:
    external: true
  jenkins:
     driver: overlay
     ipam:
      config:
      - subnet: 172.29.0.0/24