version: "3"  
services:  
  monitoring:
    image: google/cadvisor:v0.24.1
    deploy:
     mode: global
     labels: 
      - "org.label-schema.group=monitoring"
    volumes:
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/:/rootfs:ro"
    networks:
      - monitoring
networks:
  traefik_traefik-net:
    external: true
  monitoring:
     driver: overlay
     ipam:
      config:
      - subnet: 172.31.0.0/24
